name: Deploy to Vercel

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    # プルリクエストがマージされた時のみ実行
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          npx vercel deploy --prod --token=$VERCEL_TOKEN
